version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #command: pytest -vv
    ports:
      - 8001:8001
    depends_on:
      - message_queue

  message_queue:
    image: rabbitmq:3-management
    ports:
      - '5672:5672' 
      - '15672:15672'
  
  stock_exchange_mocker:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 stock_exchange_mocker/main.py
    depends_on:
      - message_queue